---
title: "PAF Shiny Simulation"
author: "Mark Klose"
date: "`r Sys.Date()`"
output: 
  html_document:
    code_folding: hide
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

## Inputs

```{r eruptions, echo=FALSE}
inputPanel(
  sliderInput("p_ws", label = "Covariate prevalence, study:",
              min=0, max=1, value=0.5, step = 0.01),
  
  sliderInput("p_as", label = "Treatment prevalence, study:", 
              min=0, max=1, value=0.4, step = 0.01), 
  
  sliderInput("p_wt", label = "Covariate prevalence, target:",
              min=0, max=1, value=0.3, step = 0.01),
  
  sliderInput("p_at", label = "Treatment prevalence, target:", 
              min=0, max=1, value=0.2, step = 0.01), 
  
  sliderInput("p_y", label = "Baseline outcome prevalence:", 
              min=0, max=1, value=0.1, step = 0.01), 
  
  sliderInput("theta_w", label = "Theta_w (for heterogeneity):", 
              min=0, max=10, value=0, step=0.1), 
  
  sliderInput("theta_y", label = "Treatment Effect (Log Odds Ratio):", 
              min=0, max=10, value=1, step=0.1), 
  
  sliderInput("n_study", label="N, study:", min=100, max=10000, value=1000, step=100), 
  
  sliderInput("n_target", label="N, study:", min=1000, max=100000, value=5000, step=1000), 
  
  sliderInput("seed", label="RNG Seed:", min=0, max=1000, value=1, step=1)
)
```

## Functions for Getting Output

### DGP 

```{r paf-functions, echo=T, collapse=TRUE}
dgp = function(s_n,
               s_treat=0.4,
               s_covariate=0.5,
               t_n,
               t_treat=0.2,
               t_covariate=0.3,
               w_coef = 0,
               treat_eff = 1,
               seed=722){
  set.seed(seed)
  study = data.frame(
    w = rbinom(n=s_n, size=1, prob=s_covariate)
  ) |>
    mutate(
      a = rbinom(n=s_n, size=1, prob = plogis(qlogis(s_treat) - mean(w) + w)),
      ya0 = rbinom(n=s_n, size=1, prob = plogis(qlogis(0.1) + w_coef * w)),
      ya1 = rbinom(n=s_n, size=1, prob = plogis(qlogis(0.1) + treat_eff + w_coef * w)),
      y = a * ya1 + (1-a) * ya0,
      pop = 0
    )

  target = data.frame(
    w = rbinom(n=t_n, size=1, prob=t_covariate)
  ) |>
    mutate(
      a = rbinom(n=t_n, size=1, prob = plogis(qlogis(t_treat) - mean(w) + w)),
      ya0 = rbinom(n=t_n, size=1, prob = plogis(qlogis(0.1) + w_coef * w)),
      ya1 = rbinom(n=t_n, size=1, prob = plogis(qlogis(0.1) + treat_eff + w_coef * w)),
      y = a * ya1 + (1-a) * ya0,
      pop = 1
    )

  bind_rows(
    study, target
  )
}
```

### True PAF

### Naive PAF

### Estimating Equations for PAF


## Output
```{r, echo=F}
renderTable({
  data = dgp(
    input$n_study, 
    input$p_as,
    input$p_ws, 
    input$n_target, 
    input$p_at, 
    input$p_wt, 
    input$theta_w, 
    input$theta_y, 
    input$seed
  ) |> 
    group_by(pop, a, w) |> 
    summarise(
      y1 = sum(y == 1), 
      y0 = sum(y == 0)
    )
  
  
})
```

